[project]
name = "openalgo-mcp"
version = "0.1.0"
description = "OpenAlgo MCP Server stub"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.12.3",
    "openalgo>=1.0.21",
]
